-- 门诊发药机接口注册脚本

delete from SYS_IMP_BASE where id = '0001Z810000000024SNY';
delete from SYS_IMP_TYPE_DESC where imid = '0001Z810000000024SNY';
delete from sys_imp_dyn_property where imid = '0001Z810000000024SNY';

Insert into SYS_IMP_BASE (ID,NAME,MODULE,IDL,REGISTRANT,REGIDATE,DESCRIPTION,ISFG,FG_SYS,DS,SV,PROCESSINFO,NAMESPACE) values ('0001Z810000000024SNY','IHisService','external-services','[]','张得建','2018-08-24 14:23:45','wsdl导入接口','Y','system',0,'2018-08-24 14:23:45', EMPTY_CLOB(),'com.founder.i');

Insert into SYS_IMP_TYPE_DESC (ID,IMID,IMTYPEID,IDL,DS,SV) values ('0001Z810000000024SNZ','0001Z810000000024SNY','1',TO_CLOB('<?xml version="1.0" encoding="utf-8"?><wsdl:definitions name="ServiceHis" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:soap="')
|| TO_CLOB('http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><wsdl:types><xs:schema elementForm')
|| TO_CLOB('Default="qualified" targetNamespace="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:element name="HelloWorld"><xs:complexType><xs:sequence/></xs:complexType></xs:element><xs:element name="HelloWorldResponse"><xs:complexType><xs:sequence><xs:element minOccurs="0" name="HelloWorldResult" nillable="true" type="xs:string"/></xs:sequence></xs:complexType></xs:element><xs:element name="HisTransData"><xs:complexType><xs:sequence><xs:element minOccurs="0" name="value" nillable="tru')
|| TO_CLOB('e" type="xs:string"/></xs:sequence></xs:complexType></xs:element><xs:element name="HisTransDataResponse"><xs:complexType><xs:sequence><xs:element minOccurs="0" name="HisTransDataResult" nillable="true" type="xs:string"/></xs:sequence></xs:complexType></xs:element></xs:schema><xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft')
|| TO_CLOB('.com/2003/10/Serialization/"><xs:element name="anyType" nillable="true" type="xs:anyType"/><xs:element name="anyURI" nillable="true" type="xs:anyURI"/><xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/><xs:element name="boolean" nillable="true" type="xs:boolean"/><xs:element name="byte" nillable="true" type="xs:byte"/><xs:element name="dateTime" nillable="true" type="xs:dateTime"/><xs:element name="decimal" nillable="true" type="xs:decimal"/><xs:element name="double" nillabl')
|| TO_CLOB('e="true" type="xs:double"/><xs:element name="float" nillable="true" type="xs:float"/><xs:element name="int" nillable="true" type="xs:int"/><xs:element name="long" nillable="true" type="xs:long"/><xs:element name="QName" nillable="true" type="xs:QName"/><xs:element name="short" nillable="true" type="xs:short"/><xs:element name="string" nillable="true" type="xs:string"/><xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/><xs:element name="unsignedInt" nillable="true" type="xs:u')
|| TO_CLOB('nsignedInt"/><xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/><xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/><xs:element name="char" nillable="true" type="tns:char"/><xs:simpleType name="char"><xs:restriction base="xs:int"/></xs:simpleType><xs:element name="duration" nillable="true" type="tns:duration"/><xs:simpleType name="duration"><xs:restriction base="xs:duration"><xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/><xs:minInclus')
|| TO_CLOB('ive value="-P10675199DT2H48M5.4775808S"/><xs:maxInclusive value="P10675199DT2H48M5.4775807S"/></xs:restriction></xs:simpleType><xs:element name="guid" nillable="true" type="tns:guid"/><xs:simpleType name="guid"><xs:restriction base="xs:string"><xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/></xs:restriction></xs:simpleType><xs:attribute name="FactoryType" type="xs:QName"/><xs:attribute name="Id" type="xs:ID"/><xs:attribute name="Ref" type="xs:IDREF"/><')
|| TO_CLOB('/xs:schema></wsdl:types><wsdl:message name="IHisService_HelloWorld_InputMessage"><wsdl:part name="parameters" element="tns:HelloWorld"/></wsdl:message><wsdl:message name="IHisService_HelloWorld_OutputMessage"><wsdl:part name="parameters" element="tns:HelloWorldResponse"/></wsdl:message><wsdl:message name="IHisService_HisTransData_InputMessage"><wsdl:part name="parameters" element="tns:HisTransData"/></wsdl:message><wsdl:message name="IHisService_HisTransData_OutputMessage"><wsdl:part name="param')
|| TO_CLOB('eters" element="tns:HisTransDataResponse"/></wsdl:message><wsdl:portType name="IHisService"><wsdl:operation name="HelloWorld"><wsdl:input wsaw:Action="http://tempuri.org/IHisService/HelloWorld" message="tns:IHisService_HelloWorld_InputMessage"/><wsdl:output wsaw:Action="http://tempuri.org/IHisService/HelloWorldResponse" message="tns:IHisService_HelloWorld_OutputMessage"/></wsdl:operation><wsdl:operation name="HisTransData"><wsdl:input wsaw:Action="http://tempuri.org/IHisService/HisTransData" mes')
|| TO_CLOB('sage="tns:IHisService_HisTransData_InputMessage"/><wsdl:output wsaw:Action="http://tempuri.org/IHisService/HisTransDataResponse" message="tns:IHisService_HisTransData_OutputMessage"/></wsdl:operation></wsdl:portType><wsdl:binding name="BasicHttpBinding_IHisService" type="tns:IHisService"><soap:binding transport="http://schemas.xmlsoap.org/soap/http"/><wsdl:operation name="HelloWorld"><soap:operation soapAction="http://tempuri.org/IHisService/HelloWorld" style="document"/><wsdl:input><soap:body u')
|| TO_CLOB('se="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output></wsdl:operation><wsdl:operation name="HisTransData"><soap:operation soapAction="http://tempuri.org/IHisService/HisTransData" style="document"/><wsdl:input><soap:body use="literal"/></wsdl:input><wsdl:output><soap:body use="literal"/></wsdl:output></wsdl:operation></wsdl:binding><wsdl:service name="ServiceHis"><wsdl:port name="BasicHttpBinding_IHisService" binding="tns:BasicHttpBinding_IHisService"><soap:address loca')
|| TO_CLOB('tion="http://192.168.13.129:8000/ConsisWebService/ServiceHis.svc"/></wsdl:port></wsdl:service></wsdl:definitions>
'),0,'2018-08-24 14:23:45');

Insert into SYS_IMP_DYN_PROPERTY (SV,PROPVALUE,DS,PROPNAME,IMID) values ('2018-11-22 15:23:37','http://192.168.13.129:8000/ConsisWebService/ServiceHis.svc?singleWsdl',0,'source','0001Z810000000024SNY');
commit;


