package iih.pmp.yilutong.i;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.15
 * 2019-01-14T16:51:02.087+08:00
 * Generated source version: 3.1.15
 * 
 */
@WebService(targetNamespace = "http://www.witontek.com/ehospital/", name = "IWindowPayWebServiceV2")
@XmlSeeAlso({ObjectFactory.class})
public interface IWindowPayWebServiceV2 {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "qryOrderStatus", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QryOrderStatus")
    @WebMethod(action = "http://www.witontek.com/ehospital/qryOrderStatus")
    @ResponseWrapper(localName = "qryOrderStatusResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QryOrderStatusResponse")
    public java.lang.String qryOrderStatus(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "scanRefund", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.ScanRefund")
    @WebMethod(action = "http://www.witontek.com/ehospital/scanRefund")
    @ResponseWrapper(localName = "scanRefundResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.ScanRefundResponse")
    public java.lang.String scanRefund(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRefundStatus", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QueryRefundStatus")
    @WebMethod(action = "http://www.witontek.com/ehospital/queryRefundStatus")
    @ResponseWrapper(localName = "queryRefundStatusResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QueryRefundStatusResponse")
    public java.lang.String queryRefundStatus(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "qrCodeReverse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QrCodeReverse")
    @WebMethod(action = "http://www.witontek.com/ehospital/qrCodeReverse")
    @ResponseWrapper(localName = "qrCodeReverseResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QrCodeReverseResponse")
    public java.lang.String qrCodeReverse(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "closeOrder", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.CloseOrder")
    @WebMethod(action = "http://www.witontek.com/ehospital/closeOrder")
    @ResponseWrapper(localName = "closeOrderResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.CloseOrderResponse")
    public java.lang.String closeOrder(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "refund", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.Refund")
    @WebMethod(action = "http://www.witontek.com/ehospital/refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.RefundResponse")
    public java.lang.String refund(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "reverseOrder", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.ReverseOrder")
    @WebMethod(action = "http://www.witontek.com/ehospital/reverseOrder")
    @ResponseWrapper(localName = "reverseOrderResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.ReverseOrderResponse")
    public java.lang.String reverseOrder(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.CreateOrder")
    @WebMethod(action = "http://www.witontek.com/ehospital/createOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.CreateOrderResponse")
    public java.lang.String createOrder(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "refundReverse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.RefundReverse")
    @WebMethod(action = "http://www.witontek.com/ehospital/refundReverse")
    @ResponseWrapper(localName = "refundReverseResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.RefundReverseResponse")
    public java.lang.String refundReverse(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "microPay", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.MicroPay")
    @WebMethod(action = "http://www.witontek.com/ehospital/microPay")
    @ResponseWrapper(localName = "microPayResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.MicroPayResponse")
    public java.lang.String microPay(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "qryPayStatus", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QryPayStatus")
    @WebMethod(action = "http://www.witontek.com/ehospital/qryPayStatus")
    @ResponseWrapper(localName = "qryPayStatusResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QryPayStatusResponse")
    public java.lang.String qryPayStatus(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "qryRefund", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QryRefund")
    @WebMethod(action = "http://www.witontek.com/ehospital/qryRefund")
    @ResponseWrapper(localName = "qryRefundResponse", targetNamespace = "http://www.witontek.com/ehospital/", className = "iih.pmp.yilutong.i.QryRefundResponse")
    public java.lang.String qryRefund(
        @WebParam(name = "inputStr", targetNamespace = "http://www.witontek.com/ehospital/")
        java.lang.String inputStr
    );
}
