package iih.ci.mr.cmisnew.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.15
 * 2019-12-09T14:31:01.459+08:00
 * Generated source version: 3.1.15
 * 
 */
@WebService(targetNamespace = "http://paser.creating.com", name = "XmlFbPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface XmlFbPortType {

    @WebResult(name = "return", targetNamespace = "http://paser.creating.com")
    @Action(input = "urn:XpServiceFb", output = "urn:XpServiceFbResponse")
    @RequestWrapper(localName = "XpServiceFb", targetNamespace = "http://paser.creating.com", className = "iih.ci.mr.cmisnew.common.XpServiceFb")
    @WebMethod(operationName = "XpServiceFb", action = "urn:XpServiceFb")
    @ResponseWrapper(localName = "XpServiceFbResponse", targetNamespace = "http://paser.creating.com", className = "iih.ci.mr.cmisnew.common.XpServiceFbResponse")
    public java.lang.String xpServiceFb(
        @WebParam(name = "xml", targetNamespace = "http://paser.creating.com")
        java.lang.String xml,
        @WebParam(name = "xmlid", targetNamespace = "http://paser.creating.com")
        java.lang.String xmlid
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "urn:parsexml", output = "urn:parsexmlResponse")
    @WebMethod(action = "urn:parsexml")
    public void parsexml();
}
