
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package iih.ci.mr.cmisnew.common;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.15
 * 2019-12-09T14:31:01.425+08:00
 * Generated source version: 3.1.15
 * 
 */

@javax.jws.WebService(
                      serviceName = "XmlFb",
                      portName = "XmlFbHttpSoap12Endpoint",
                      targetNamespace = "http://paser.creating.com",
                      wsdlLocation = "file:/root/AppData/interface_manage/0001Z8100000001C0YB5/webservice/java/XmlFbPortType.wsdl",
                      endpointInterface = "iih.ci.mr.cmisnew.common.XmlFbPortType")
                      
public class XmlFbHttpSoap12EndpointImpl implements XmlFbPortType {

    private static final Logger LOG = Logger.getLogger(XmlFbHttpSoap12EndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see iih.ci.mr.cmisnew.common.XmlFbPortType#xpServiceFb(java.lang.String xml, java.lang.String xmlid)*
     */
    public java.lang.String xpServiceFb(java.lang.String xml, java.lang.String xmlid) { 
        LOG.info("Executing operation xpServiceFb");
        System.out.println(xml);
        System.out.println(xmlid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.ci.mr.cmisnew.common.XmlFbPortType#parsexml()*
     */
    public void parsexml() { 
        LOG.info("Executing operation parsexml");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
