package iih.pmp.yilutong.i;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.15
 * 2019-01-14T16:51:02.101+08:00
 * Generated source version: 3.1.15
 * 
 */
@WebServiceClient(name = "WindowPayWebServiceImplV2Service", 
                  wsdlLocation = "file:/root/AppData/interface_manage/0001LL1000000006ZVE7/webservice/java/IWindowPayWebServiceV2.wsdl",
                  targetNamespace = "http://www.witontek.com/ehospital/") 
public class WindowPayWebServiceImplV2Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.witontek.com/ehospital/", "WindowPayWebServiceImplV2Service");
    public final static QName WindowPayWebServiceImplV2Port = new QName("http://www.witontek.com/ehospital/", "WindowPayWebServiceImplV2Port");
    static {
        URL url = null;
        try {
            url = new URL("file:/root/AppData/interface_manage/0001LL1000000006ZVE7/webservice/java/IWindowPayWebServiceV2.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WindowPayWebServiceImplV2Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/root/AppData/interface_manage/0001LL1000000006ZVE7/webservice/java/IWindowPayWebServiceV2.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WindowPayWebServiceImplV2Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WindowPayWebServiceImplV2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WindowPayWebServiceImplV2Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WindowPayWebServiceImplV2Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WindowPayWebServiceImplV2Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WindowPayWebServiceImplV2Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IWindowPayWebServiceV2
     */
    @WebEndpoint(name = "WindowPayWebServiceImplV2Port")
    public IWindowPayWebServiceV2 getWindowPayWebServiceImplV2Port() {
        return super.getPort(WindowPayWebServiceImplV2Port, IWindowPayWebServiceV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWindowPayWebServiceV2
     */
    @WebEndpoint(name = "WindowPayWebServiceImplV2Port")
    public IWindowPayWebServiceV2 getWindowPayWebServiceImplV2Port(WebServiceFeature... features) {
        return super.getPort(WindowPayWebServiceImplV2Port, IWindowPayWebServiceV2.class, features);
    }

}
