
package iih.ci.mr.cmis.common;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XmlFb", targetNamespace = "http://paser.creating.com", wsdlLocation = "http://192.168.0.77:8080/ewd/services/XmlFb?wsdl")
public class XmlFb
    extends Service
{

    private final static URL XMLFB_WSDL_LOCATION;
    private final static WebServiceException XMLFB_EXCEPTION;
    private final static QName XMLFB_QNAME = new QName("http://paser.creating.com", "XmlFb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.77:8080/ewd/services/XmlFb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XMLFB_WSDL_LOCATION = url;
        XMLFB_EXCEPTION = e;
    }

    public XmlFb() {
        super(__getWsdlLocation(), XMLFB_QNAME);
    }

    public XmlFb(WebServiceFeature... features) {
        super(__getWsdlLocation(), XMLFB_QNAME, features);
    }

    public XmlFb(URL wsdlLocation) {
        super(wsdlLocation, XMLFB_QNAME);
    }

    public XmlFb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XMLFB_QNAME, features);
    }

    public XmlFb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XmlFb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns XmlFbPortType
     */
    @WebEndpoint(name = "XmlFbHttpSoap11Endpoint")
    public XmlFbPortType getXmlFbHttpSoap11Endpoint() {
        return super.getPort(new QName("http://paser.creating.com", "XmlFbHttpSoap11Endpoint"), XmlFbPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XmlFbPortType
     */
    @WebEndpoint(name = "XmlFbHttpSoap11Endpoint")
    public XmlFbPortType getXmlFbHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://paser.creating.com", "XmlFbHttpSoap11Endpoint"), XmlFbPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XMLFB_EXCEPTION!= null) {
            throw XMLFB_EXCEPTION;
        }
        return XMLFB_WSDL_LOCATION;
    }

}
