
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package iih.pmp.yilutong.i;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.15
 * 2019-01-14T16:51:02.064+08:00
 * Generated source version: 3.1.15
 * 
 */

@javax.jws.WebService(
                      serviceName = "WindowPayWebServiceImplV2Service",
                      portName = "WindowPayWebServiceImplV2Port",
                      targetNamespace = "http://www.witontek.com/ehospital/",
                      wsdlLocation = "file:/root/AppData/interface_manage/0001LL1000000006ZVE7/webservice/java/IWindowPayWebServiceV2.wsdl",
                      endpointInterface = "iih.pmp.yilutong.i.IWindowPayWebServiceV2")
                      
public class WindowPayWebServiceImplV2PortImpl implements IWindowPayWebServiceV2 {

    private static final Logger LOG = Logger.getLogger(WindowPayWebServiceImplV2PortImpl.class.getName());

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#qryOrderStatus(java.lang.String inputStr)*
     */
    public java.lang.String qryOrderStatus(java.lang.String inputStr) { 
        LOG.info("Executing operation qryOrderStatus");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#scanRefund(java.lang.String inputStr)*
     */
    public java.lang.String scanRefund(java.lang.String inputStr) { 
        LOG.info("Executing operation scanRefund");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#queryRefundStatus(java.lang.String inputStr)*
     */
    public java.lang.String queryRefundStatus(java.lang.String inputStr) { 
        LOG.info("Executing operation queryRefundStatus");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#qrCodeReverse(java.lang.String inputStr)*
     */
    public java.lang.String qrCodeReverse(java.lang.String inputStr) { 
        LOG.info("Executing operation qrCodeReverse");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#closeOrder(java.lang.String inputStr)*
     */
    public java.lang.String closeOrder(java.lang.String inputStr) { 
        LOG.info("Executing operation closeOrder");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#refund(java.lang.String inputStr)*
     */
    public java.lang.String refund(java.lang.String inputStr) { 
        LOG.info("Executing operation refund");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#reverseOrder(java.lang.String inputStr)*
     */
    public java.lang.String reverseOrder(java.lang.String inputStr) { 
        LOG.info("Executing operation reverseOrder");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#createOrder(java.lang.String inputStr)*
     */
    public java.lang.String createOrder(java.lang.String inputStr) { 
        LOG.info("Executing operation createOrder");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#refundReverse(java.lang.String inputStr)*
     */
    public java.lang.String refundReverse(java.lang.String inputStr) { 
        LOG.info("Executing operation refundReverse");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#microPay(java.lang.String inputStr)*
     */
    public java.lang.String microPay(java.lang.String inputStr) { 
        LOG.info("Executing operation microPay");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#qryPayStatus(java.lang.String inputStr)*
     */
    public java.lang.String qryPayStatus(java.lang.String inputStr) { 
        LOG.info("Executing operation qryPayStatus");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see iih.pmp.yilutong.i.IWindowPayWebServiceV2#qryRefund(java.lang.String inputStr)*
     */
    public java.lang.String qryRefund(java.lang.String inputStr) { 
        LOG.info("Executing operation qryRefund");
        System.out.println(inputStr);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
